In [1]:
import sqlite3
import pandas as pd

In [2]:
con = sqlite3.connect('../data/raw/ipl.db')

def query(sql):
    return pd.read_sql(sql,con)

In [3]:
query('SELECT COUNT(*) AS total_matches FROM matches;')

   total_matches
0           1212

In [4]:
query('''SELECT DISTINCT season
FROM matches;
''')

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [6]:
query('''SELECT DISTINCT match_id
FROM deliveries;
''')

      match_id
0       335982
1       335983
2       335984
3       335985
4       335986
...        ...
1207   1529282
1208   1529283
1209   1529284
1210   1529285
1211   1529286

[1212 rows x 1 columns]

In [7]:
query('''SELECT DISTINCT bowler_type
FROM deliveries;
''')

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                            None

In [13]:
query('''
SELECT match_id,city,match_winner
FROM matches
WHERE match_winner='Mumbai Indians'
LIMIT 10;
''')

   match_id       city    match_winner
0   1082597     Mumbai  Mumbai Indians
1   1082600     Mumbai  Mumbai Indians
2   1082602  Bangalore  Mumbai Indians
3   1082606     Mumbai  Mumbai Indians
4   1082612     Indore  Mumbai Indians
5   1082614     Mumbai  Mumbai Indians
6   1082625     Rajkot  Mumbai Indians
7   1082628     Mumbai  Mumbai Indians
8   1082635      Delhi  Mumbai Indians
9   1082644    Kolkata  Mumbai Indians

In [15]:
query('''
SELECT match_date,venue,match_winner
FROM matches
WHERE season='2018';
''')

,match_date,venue,match_winner
0,2018-04-07,Wankhede Stadium,Chennai Super Kings
1,2018-04-08,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
2,2018-04-08,Eden Gardens,Kolkata Knight Riders
3,2018-04-09,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
4,2018-04-10,MA Chidambaram Stadium,Chennai Super Kings
5,2018-04-11,Sawai Mansingh Stadium,Rajasthan Royals
6,2018-04-12,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
7,2018-04-13,M.Chinnaswamy Stadium,Royal Challengers Bangalore
8,2018-04-14,Wankhede Stadium,Delhi Capitals
9,2018-04-14,Eden Gardens,Sunrisers Hyderabad
10,2018-04-15,M.Chinnaswamy Stadium,Rajasthan Royals
11,2018-04-15,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
12,2018-04-16,Eden Gardens,Kolkata Knight Riders
13,2018-04-17,Wankhede Stadium,Mumbai Indians
14,2018-04-18,Sawai Mansingh Stadium,Kolkata Knight Riders
15,2018-04-19,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
16,2018-04-20,Maharashtra Cricket Association Stadium,Chennai Super Kings
17,2018-04-21,Eden Gardens,Punjab Kings
18,2018-04-21,M.Chinnaswamy Stadium,Royal Challengers Bangalore
19,2018-04-22,Rajiv Gandhi International Stadium,Chennai Super Kings
20,2018-04-22,Sawai Mansingh Stadium,Rajasthan Royals
21,2018-04-23,Arun Jaitley Stadium,Punjab Kings
22,2018-04-24,Wankhede Stadium,Sunrisers Hyderabad
23,2018-04-25,M.Chinnaswamy Stadium,Chennai Super Kings
24,2018-04-26,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
25,2018-04-27,Arun Jaitley Stadium,Delhi Capitals
26,2018-04-28,Maharashtra Cricket Association Stadium,Mumbai Indians
27,2018-04-29,Sawai Mansingh Stadium,Sunrisers Hyderabad
28,2018-04-29,M.Chinnaswamy Stadium,Kolkata Knight Riders
29,2018-04-30,Maharashtra Cricket Association Stadium,Chennai Super Kings
30,2018-05-01,M.Chinnaswamy Stadium,Royal Challengers Bangalore
31,2018-05-02,Arun Jaitley Stadium,Delhi Capitals
32,2018-05-03,Eden Gardens,Kolkata Knight Riders
33,2018-05-04,Holkar Cricket Stadium,Mumbai Indians
34,2018-05-05,Maharashtra Cricket Association Stadium,Chennai Super Kings
35,2018-05-05,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
36,2018-05-06,Wankhede Stadium,Mumbai Indians
37,2018-05-06,Holkar Cricket Stadium,Punjab Kings
38,2018-05-07,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
39,2018-05-08,Sawai Mansingh Stadium,Rajasthan Royals
40,2018-05-09,Eden Gardens,Mumbai Indians
41,2018-05-10,Arun Jaitley Stadium,Sunrisers Hyderabad
42,2018-05-11,Sawai Mansingh Stadium,Rajasthan Royals
43,2018-05-12,Holkar Cricket Stadium,Kolkata Knight Riders
44,2018-05-12,Arun Jaitley Stadium,Royal Challengers Bangalore
45,2018-05-13,Maharashtra Cricket Association Stadium,Chennai Super Kings
46,2018-05-13,Wankhede Stadium,Rajasthan Royals
47,2018-05-14,Holkar Cricket Stadium,Royal Challengers Bangalore
48,2018-05-15,Eden Gardens,Kolkata Knight Riders
49,2018-05-16,Wankhede Stadium,Mumbai Indians
50,2018-05-17,M.Chinnaswamy Stadium,Royal Challengers Bangalore
51,2018-05-18,Arun Jaitley Stadium,Delhi Capitals
52,2018-05-19,Sawai Mansingh Stadium,Rajasthan Royals
53,2018-05-19,Rajiv Gandhi International Stadium,Kolkata Knight Riders
54,2018-05-20,Arun Jaitley Stadium,Delhi Capitals
55,2018-05-20,Maharashtra Cricket Association Stadium,Chennai Super Kings
56,2018-05-22,Wankhede Stadium,Chennai Super Kings
57,2018-05-23,Eden Gardens,Kolkata Knight Riders
58,2018-05-25,Eden Gardens,Sunrisers Hyderabad
59,2018-05-27,Wankhede Stadium,Chennai Super Kings

In [17]:
query('''
SELECT match_id,venue,city,season
FROM matches
WHERE city='Mumbai';
''')

     match_id                     venue    city season
0     1082597          Wankhede Stadium  Mumbai   2017
1     1082600          Wankhede Stadium  Mumbai   2017
2     1082606          Wankhede Stadium  Mumbai   2017
3     1082614          Wankhede Stadium  Mumbai   2017
4     1082618          Wankhede Stadium  Mumbai   2017
..        ...                       ...     ...    ...
180   1527675  Wankhede Stadium, Mumbai  Mumbai   2026
181   1527693  Wankhede Stadium, Mumbai  Mumbai   2026
182   1529267  Wankhede Stadium, Mumbai  Mumbai   2026
183   1529276  Wankhede Stadium, Mumbai  Mumbai   2026
184   1529284  Wankhede Stadium, Mumbai  Mumbai   2026

[185 rows x 4 columns]

In [21]:
query('''
SELECT match_id,season,match_winner,win_by_runs
FROM matches
WHERE win_by_runs >= 100
ORDER BY win_by_runs;
''')

    match_id season                 match_winner  win_by_runs
0    1473487   2025               Mumbai Indians        100.0
1    1136601   2018               Mumbai Indians        102.0
2    1529276   2026          Chennai Super Kings        103.0
3     336038   2008             Rajasthan Royals        105.0
4    1422134   2024        Kolkata Knight Riders        106.0
5    1473505   2025          Sunrisers Hyderabad        110.0
6     501260   2011                 Punjab Kings        111.0
7    1359534   2023  Royal Challengers Bangalore        112.0
8    1175366   2019          Sunrisers Hyderabad        118.0
9     598027   2013  Royal Challengers Bangalore        130.0
10    829785   2015  Royal Challengers Bangalore        138.0
11    335982   2008        Kolkata Knight Riders        140.0
12    980987   2016  Royal Challengers Bangalore        144.0
13   1082635   2017               Mumbai Indians        146.0

In [22]:
query('''
SELECT match_id,season,team1,team2
FROM matches
WHERE match_winner IS NULL;
''')

Empty DataFrame
Columns: [match_id, season, team1, team2]
Index: []

In [24]:
query('''
SELECT match_id,venue,match_winner
FROM matches
ORDER BY match_date DESC
LIMIT 10;
''')

,match_id,venue,match_winner
0,1529286,"Sawai Mansingh Stadium, Jaipur",Delhi Capitals
1,1529285,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans
2,1529284,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad
3,1529283,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals
4,1529282,"Arun Jaitley Stadium, Delhi",Royal Challengers Bangalore
5,1529280,"MA Chidambaram Stadium, Chepauk, Chennai",Gujarat Titans
6,1529281,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants
7,1529278,"Arun Jaitley Stadium, Delhi",Punjab Kings
8,1529279,"Sawai Mansingh Stadium, Jaipur",Sunrisers Hyderabad
9,1529277,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore

In [25]:
query('''
SELECT DISTINCT d.batter
FROM deliveries AS d
LEFT JOIN players AS p
    ON p.player_name = d.batter
WHERE p.player_name IS NULL
ORDER BY d.batter;
''')

Empty DataFrame
Columns: [batter]
Index: []